name: Run Postman Tests and Deploy Results

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install Newman and HTML reporter
      run: |
        npm i

    - name: Create results directory
      run: mkdir -p ./testResults

    - name: Run Postman collection with HTML report
      run: |
        npx newman run petstore.collection.json \
          --reporters html,cli \
          --reporter-html-export ./testResults/index.html \
          --suppress-exit-code
        # Fallback if HTML reporter fails
        if [ ! -f ./testResults/index.html ]; then
          echo "Creating fallback report..."
          echo "<h1>Test Results</h1><pre>$(newman run petstore.collection.json --reporters cli)</pre>" > ./testResults/index.html
        fi

    - name: Verify report generation
      run: |
        echo "Contents of testResults directory:"
        ls -la ./testResults
        [ -f ./testResults/index.html ] || exit 1

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./testResults
        force_orphan: true
        user_name: 'GitHub Actions Bot'
        user_email: '41898282+github-actions[bot]@users.noreply.github.com'